# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

from pyqtgraph import PlotWidget
import numpy as np


class Ui_DCM(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QSize(1000, 500))
        MainWindow.setStyleSheet(u"background-color: rgb(45, 45, 45);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Top_Bar = QFrame(self.centralwidget)
        self.Top_Bar.setObjectName(u"Top_Bar")
        self.Top_Bar.setMaximumSize(QSize(16777215, 40))
        self.Top_Bar.setStyleSheet(u"background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_toggle = QFrame(self.Top_Bar)
        self.frame_toggle.setObjectName(u"frame_toggle")
        self.frame_toggle.setMaximumSize(QSize(70, 40))
        self.frame_toggle.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Btn_Toggle = QPushButton(self.frame_toggle)
        self.Btn_Toggle.setObjectName(u"Btn_Toggle")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border: 0px solid;")

        self.verticalLayout_2.addWidget(self.Btn_Toggle)


        self.horizontalLayout.addWidget(self.frame_toggle)

        self.frame_top = QFrame(self.Top_Bar)
        self.frame_top.setObjectName(u"frame_top")
        self.frame_top.setFrameShape(QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_top)


        self.verticalLayout.addWidget(self.Top_Bar)

        self.Content = QFrame(self.centralwidget)
        self.Content.setObjectName(u"Content")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_left_menu = QFrame(self.Content)
        self.frame_left_menu.setObjectName(u"frame_left_menu")
        self.frame_left_menu.setMinimumSize(QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet(u"background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_top_menus = QFrame(self.frame_left_menu)
        self.frame_top_menus.setObjectName(u"frame_top_menus")
        self.frame_top_menus.setFrameShape(QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_page_1 = QPushButton(self.frame_top_menus)
        self.btn_page_1.setObjectName(u"btn_page_1")
        self.btn_page_1.setMinimumSize(QSize(0, 40))
        self.btn_page_1.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_page_1)

        self.btn_page_2 = QPushButton(self.frame_top_menus)
        self.btn_page_2.setObjectName(u"btn_page_2")
        self.btn_page_2.setMinimumSize(QSize(0, 40))
        self.btn_page_2.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_page_2)

        self.btn_page_3 = QPushButton(self.frame_top_menus)
        self.btn_page_3.setObjectName(u"btn_page_3")
        self.btn_page_3.setMinimumSize(QSize(0, 40))
        self.btn_page_3.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_page_3)

        self.btn_page_4 = QPushButton(self.frame_top_menus)
        self.btn_page_4.setObjectName(u"btn_page_4")
        self.btn_page_4.setMinimumSize(QSize(0, 40))
        self.btn_page_4.setStyleSheet(u"QPushButton{\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(35, 35, 35);\n"
"	border: 0px solid;\n"
"}\n"
"QPushButton:hover{\n"
"	background-color: rgb(85, 170, 255);\n"
"}")

        self.verticalLayout_4.addWidget(self.btn_page_4)


        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, Qt.AlignTop)


        self.horizontalLayout_2.addWidget(self.frame_left_menu)

        self.frame_pages = QFrame(self.Content)
        self.frame_pages.setObjectName(u"frame_pages")
        self.frame_pages.setFrameShape(QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.stackedWidget = QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.groupBox = QGroupBox(self.page_1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 20, 541, 201))
        self.groupBox.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 30, 111, 16))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 70, 111, 16))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 110, 101, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 150, 111, 16))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(260, 30, 131, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(260, 70, 141, 16))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(360, 110, 55, 16))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(360, 150, 55, 16))
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(140, 30, 42, 22))
        self.spinBox_2 = QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(140, 70, 42, 22))
        self.spinBox_3 = QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(140, 110, 42, 22))
        self.spinBox_4 = QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(140, 150, 42, 22))
        self.spinBox_5 = QSpinBox(self.groupBox)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(410, 30, 42, 22))
        self.spinBox_6 = QSpinBox(self.groupBox)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(410, 70, 42, 22))
        self.spinBox_7 = QSpinBox(self.groupBox)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(410, 110, 42, 22))
        self.spinBox_8 = QSpinBox(self.groupBox)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(410, 150, 42, 22))
        self.label_11 = QLabel(self.page_1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(400, 0, 81, 16))
        self.label_11.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.graphicsView = QGraphicsView(self.page_1)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 230, 651, 201))
        self.pushButton = QPushButton(self.page_1)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(690, 40, 161, 41))
        self.pushButton.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2 = QPushButton(self.page_1)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(690, 100, 161, 41))
        self.pushButton_2.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.groupBox_2 = QGroupBox(self.page_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 20, 501, 191))
        self.groupBox_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 30, 101, 16))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(30, 70, 101, 16))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 110, 101, 16))
        self.label_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 150, 111, 16))
        self.label_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 30, 131, 16))
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 70, 141, 16))
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_16 = QLabel(self.groupBox_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(250, 110, 31, 16))
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_17 = QLabel(self.groupBox_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 150, 31, 16))
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_9 = QSpinBox(self.groupBox_2)
        self.spinBox_9.setObjectName(u"spinBox_9")
        self.spinBox_9.setGeometry(QRect(150, 30, 42, 22))
        self.spinBox_9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_11 = QSpinBox(self.groupBox_2)
        self.spinBox_11.setObjectName(u"spinBox_11")
        self.spinBox_11.setGeometry(QRect(150, 110, 42, 22))
        self.spinBox_11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_12 = QSpinBox(self.groupBox_2)
        self.spinBox_12.setObjectName(u"spinBox_12")
        self.spinBox_12.setGeometry(QRect(150, 150, 42, 22))
        self.spinBox_12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_13 = QSpinBox(self.groupBox_2)
        self.spinBox_13.setObjectName(u"spinBox_13")
        self.spinBox_13.setGeometry(QRect(400, 30, 42, 22))
        self.spinBox_13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_14 = QSpinBox(self.groupBox_2)
        self.spinBox_14.setObjectName(u"spinBox_14")
        self.spinBox_14.setGeometry(QRect(400, 70, 42, 22))
        self.spinBox_14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_15 = QSpinBox(self.groupBox_2)
        self.spinBox_15.setObjectName(u"spinBox_15")
        self.spinBox_15.setGeometry(QRect(290, 110, 42, 22))
        self.spinBox_15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_16 = QSpinBox(self.groupBox_2)
        self.spinBox_16.setObjectName(u"spinBox_16")
        self.spinBox_16.setGeometry(QRect(290, 150, 42, 22))
        self.spinBox_16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_10 = QSpinBox(self.groupBox_2)
        self.spinBox_10.setObjectName(u"spinBox_10")
        self.spinBox_10.setGeometry(QRect(150, 70, 42, 22))
        self.spinBox_10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_3 = QPushButton(self.page_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(630, 40, 141, 41))
        self.pushButton_3.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4 = QPushButton(self.page_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(630, 100, 141, 41))
        self.pushButton_4.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.graphicsView_2 = QGraphicsView(self.page_2)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(0, 220, 621, 211))
        self.label_18 = QLabel(self.page_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(400, 0, 71, 16))
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_18.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.groupBox_3 = QGroupBox(self.page_3)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(0, 20, 521, 171))
        self.groupBox_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_19 = QLabel(self.groupBox_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 100, 101, 16))
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_17 = QSpinBox(self.groupBox_3)
        self.spinBox_17.setObjectName(u"spinBox_17")
        self.spinBox_17.setGeometry(QRect(390, 20, 42, 22))
        self.spinBox_17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_20 = QLabel(self.groupBox_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(240, 20, 131, 16))
        self.label_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_21 = QLabel(self.groupBox_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 20, 101, 16))
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_22 = QLabel(self.groupBox_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(20, 60, 101, 16))
        self.label_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_18 = QSpinBox(self.groupBox_3)
        self.spinBox_18.setObjectName(u"spinBox_18")
        self.spinBox_18.setGeometry(QRect(140, 140, 42, 22))
        self.spinBox_18.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_23 = QLabel(self.groupBox_3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(240, 60, 141, 16))
        self.label_23.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_19 = QSpinBox(self.groupBox_3)
        self.spinBox_19.setObjectName(u"spinBox_19")
        self.spinBox_19.setGeometry(QRect(140, 60, 42, 22))
        self.spinBox_19.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_24 = QLabel(self.groupBox_3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(240, 140, 31, 16))
        self.label_24.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_20 = QSpinBox(self.groupBox_3)
        self.spinBox_20.setObjectName(u"spinBox_20")
        self.spinBox_20.setGeometry(QRect(140, 20, 42, 22))
        self.spinBox_20.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_21 = QSpinBox(self.groupBox_3)
        self.spinBox_21.setObjectName(u"spinBox_21")
        self.spinBox_21.setGeometry(QRect(140, 100, 42, 22))
        self.spinBox_21.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_25 = QLabel(self.groupBox_3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(240, 100, 31, 16))
        self.label_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_22 = QSpinBox(self.groupBox_3)
        self.spinBox_22.setObjectName(u"spinBox_22")
        self.spinBox_22.setGeometry(QRect(390, 60, 42, 22))
        self.spinBox_22.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_26 = QLabel(self.groupBox_3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 140, 111, 16))
        self.label_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_23 = QSpinBox(self.groupBox_3)
        self.spinBox_23.setObjectName(u"spinBox_23")
        self.spinBox_23.setGeometry(QRect(290, 100, 42, 22))
        self.spinBox_24 = QSpinBox(self.groupBox_3)
        self.spinBox_24.setObjectName(u"spinBox_24")
        self.spinBox_24.setGeometry(QRect(290, 140, 42, 22))
        self.graphicsView_3 = QGraphicsView(self.page_3)
        self.graphicsView_3.setObjectName(u"graphicsView_3")
        self.graphicsView_3.setGeometry(QRect(0, 200, 661, 231))
        self.pushButton_5 = QPushButton(self.page_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(720, 50, 151, 41))
        self.pushButton_5.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6 = QPushButton(self.page_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(720, 120, 151, 41))
        self.pushButton_6.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_27 = QLabel(self.page_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(420, 0, 71, 16))
        self.label_27.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_27.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.groupBox_4 = QGroupBox(self.page_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(0, 20, 521, 171))
        self.groupBox_4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_28 = QLabel(self.groupBox_4)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 100, 101, 16))
        self.label_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_25 = QSpinBox(self.groupBox_4)
        self.spinBox_25.setObjectName(u"spinBox_25")
        self.spinBox_25.setGeometry(QRect(390, 20, 42, 22))
        self.spinBox_25.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_29 = QLabel(self.groupBox_4)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(240, 20, 131, 16))
        self.label_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_30 = QLabel(self.groupBox_4)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 20, 101, 16))
        self.label_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_31 = QLabel(self.groupBox_4)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 60, 101, 16))
        self.label_31.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_26 = QSpinBox(self.groupBox_4)
        self.spinBox_26.setObjectName(u"spinBox_26")
        self.spinBox_26.setGeometry(QRect(140, 140, 42, 22))
        self.spinBox_26.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_32 = QLabel(self.groupBox_4)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(240, 60, 141, 16))
        self.label_32.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_27 = QSpinBox(self.groupBox_4)
        self.spinBox_27.setObjectName(u"spinBox_27")
        self.spinBox_27.setGeometry(QRect(140, 60, 42, 22))
        self.spinBox_27.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_33 = QLabel(self.groupBox_4)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(240, 140, 31, 16))
        self.label_33.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_28 = QSpinBox(self.groupBox_4)
        self.spinBox_28.setObjectName(u"spinBox_28")
        self.spinBox_28.setGeometry(QRect(140, 20, 42, 22))
        self.spinBox_28.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_29 = QSpinBox(self.groupBox_4)
        self.spinBox_29.setObjectName(u"spinBox_29")
        self.spinBox_29.setGeometry(QRect(140, 100, 42, 22))
        self.spinBox_29.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_34 = QLabel(self.groupBox_4)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(240, 100, 31, 16))
        self.label_34.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_30 = QSpinBox(self.groupBox_4)
        self.spinBox_30.setObjectName(u"spinBox_30")
        self.spinBox_30.setGeometry(QRect(390, 60, 42, 22))
        self.spinBox_30.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_35 = QLabel(self.groupBox_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(20, 140, 111, 16))
        self.label_35.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.spinBox_31 = QSpinBox(self.groupBox_4)
        self.spinBox_31.setObjectName(u"spinBox_31")
        self.spinBox_31.setGeometry(QRect(290, 100, 42, 22))
        self.spinBox_32 = QSpinBox(self.groupBox_4)
        self.spinBox_32.setObjectName(u"spinBox_32")
        self.spinBox_32.setGeometry(QRect(290, 140, 42, 22))
        self.graphicsView_4 = PlotWidget(self.page_4)
        self.graphicsView_4.setObjectName(u"graphicsView_4")
        self.graphicsView_4.setGeometry(QRect(0, 200, 671, 231))
        self.pushButton_7 = QPushButton(self.page_4)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(710, 120, 151, 41))
        self.pushButton_7.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8 = QPushButton(self.page_4)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(710, 50, 151, 41))
        self.pushButton_8.setStyleSheet(u"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label_36 = QLabel(self.page_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(410, 0, 71, 16))
        self.label_36.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_36.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_4)

        self.verticalLayout_5.addWidget(self.stackedWidget)


        self.horizontalLayout_2.addWidget(self.frame_pages)


        self.verticalLayout.addWidget(self.Content)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)


        self.pushButton.clicked.connect(lambda:self.draw())
        self.pushButton_2.clicked.connect(lambda:self.clear())


    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Btn_Toggle.setText(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.btn_page_1.setText(QCoreApplication.translate("MainWindow", u"AOO", None))
        self.btn_page_2.setText(QCoreApplication.translate("MainWindow", u"VOO", None))
        self.btn_page_3.setText(QCoreApplication.translate("MainWindow", u"AAI", None))
        self.btn_page_4.setText(QCoreApplication.translate("MainWindow", u"VVI", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"AOO", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"VOO", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"AAI", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"VVI", None))
    # retranslateUi


    def draw(self):
        x = np.random.normal(size=1000)
        y = np.random.normal(size=(3,1000))
        for i in range(3):
            self.graphicsView.plot(x,y[i],pen=(i,3))

    def clear(self):
        self.graphicsView.clear()

