# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QHBoxLayout,
    QLabel, QMainWindow, QPushButton, QSizePolicy,
    QSpinBox, QStackedWidget, QVBoxLayout, QWidget)

from pyqtgraph import PlotWidget
import numpy as np

class Ui_MainWindow(object):
    def __inti__(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1000, 500)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.Top_Bar = QFrame(self.centralwidget)
        self.Top_Bar.setObjectName(u"Top_Bar")
        self.Top_Bar.setMaximumSize(QSize(16777215, 40))
        self.Top_Bar.setAutoFillBackground(False)
        self.Top_Bar.setStyleSheet(u"background-color: rgb(45, 45, 45);")
        self.Top_Bar.setFrameShape(QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.frame_toggle = QFrame(self.Top_Bar)
        self.frame_toggle.setObjectName(u"frame_toggle")
        self.frame_toggle.setMaximumSize(QSize(70, 40))
        self.frame_toggle.setStyleSheet(u"background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.Btn_Toggle = QPushButton(self.frame_toggle)
        self.Btn_Toggle.setObjectName(u"Btn_Toggle")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border: 0px solid;")

        self.verticalLayout_2.addWidget(self.Btn_Toggle)


        self.horizontalLayout.addWidget(self.frame_toggle)

        self.frame_top = QFrame(self.Top_Bar)
        self.frame_top.setObjectName(u"frame_top")
        self.frame_top.setFrameShape(QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QFrame.Raised)

        self.horizontalLayout.addWidget(self.frame_top)


        self.verticalLayout.addWidget(self.Top_Bar)

        self.Content = QFrame(self.centralwidget)
        self.Content.setObjectName(u"Content")
        self.Content.setStyleSheet(u"background-color: rgb(72, 72, 72);")
        self.Content.setFrameShape(QFrame.NoFrame)
        self.Content.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.Content)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_left_menu = QFrame(self.Content)
        self.frame_left_menu.setObjectName(u"frame_left_menu")
        self.frame_left_menu.setMinimumSize(QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet(u"background-color: rgb(45, 45, 45);")
        self.frame_left_menu.setFrameShape(QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_top_menus = QFrame(self.frame_left_menu)
        self.frame_top_menus.setObjectName(u"frame_top_menus")
        self.frame_top_menus.setFrameShape(QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.btn_page_4 = QPushButton(self.frame_top_menus)
        self.btn_page_4.setObjectName(u"btn_page_4")
        self.btn_page_4.setMinimumSize(QSize(0, 40))
        self.btn_page_4.setStyleSheet(u"QPushButton{\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border: 0px solid;\n"
"}\n"
"")

        self.verticalLayout_4.addWidget(self.btn_page_4)

        self.btn_page_3 = QPushButton(self.frame_top_menus)
        self.btn_page_3.setObjectName(u"btn_page_3")
        self.btn_page_3.setMinimumSize(QSize(0, 40))
        self.btn_page_3.setStyleSheet(u"QPushButton{\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border: 0px solid;\n"
"}\n"
"")

        self.verticalLayout_4.addWidget(self.btn_page_3)

        self.btn_page_2 = QPushButton(self.frame_top_menus)
        self.btn_page_2.setObjectName(u"btn_page_2")
        self.btn_page_2.setMinimumSize(QSize(0, 40))
        self.btn_page_2.setStyleSheet(u"QPushButton{\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border: 0px solid;\n"
"}\n"
"")

        self.verticalLayout_4.addWidget(self.btn_page_2)

        self.btn_page_1 = QPushButton(self.frame_top_menus)
        self.btn_page_1.setObjectName(u"btn_page_1")
        self.btn_page_1.setMinimumSize(QSize(0, 40))
        self.btn_page_1.setStyleSheet(u"QPushButton{\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border: 0px solid;\n"
"}\n"
"")

        self.verticalLayout_4.addWidget(self.btn_page_1)


        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, Qt.AlignTop)


        self.horizontalLayout_2.addWidget(self.frame_left_menu)

        self.frame_pages = QFrame(self.Content)
        self.frame_pages.setObjectName(u"frame_pages")
        self.frame_pages.setFrameShape(QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.Pages_Widget = QStackedWidget(self.frame_pages)
        self.Pages_Widget.setObjectName(u"Pages_Widget")
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.pushButton_13 = QPushButton(self.page_1)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(660, 50, 181, 51))
        self.pushButton_13.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_55 = QLabel(self.page_1)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(390, -10, 111, 31))
        self.label_55.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";\n"
"")
        self.label_55.setAlignment(Qt.AlignCenter)
        self.graphicsView_7 = PlotWidget(self.page_1)
        self.graphicsView_7.setObjectName(u"graphicsView_7")
        self.graphicsView_7.setGeometry(QRect(0, 210, 631, 221))
        self.pushButton_14 = QPushButton(self.page_1)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(660, 130, 181, 51))
        self.pushButton_14.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.groupBox_7 = QGroupBox(self.page_1)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(0, 20, 561, 181))
        self.groupBox_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_56 = QLabel(self.groupBox_7)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(20, 30, 101, 21))
        self.label_57 = QLabel(self.groupBox_7)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(20, 70, 101, 21))
        self.label_58 = QLabel(self.groupBox_7)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(20, 110, 101, 20))
        self.label_59 = QLabel(self.groupBox_7)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(20, 150, 101, 16))
        self.label_60 = QLabel(self.groupBox_7)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(230, 30, 121, 16))
        self.label_61 = QLabel(self.groupBox_7)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(230, 70, 131, 16))
        self.label_62 = QLabel(self.groupBox_7)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(320, 110, 31, 16))
        self.label_63 = QLabel(self.groupBox_7)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(320, 150, 31, 16))
        self.spinBox_49 = QSpinBox(self.groupBox_7)
        self.spinBox_49.setObjectName(u"spinBox_49")
        self.spinBox_49.setGeometry(QRect(130, 30, 42, 22))
        self.spinBox_50 = QSpinBox(self.groupBox_7)
        self.spinBox_50.setObjectName(u"spinBox_50")
        self.spinBox_50.setGeometry(QRect(130, 70, 42, 22))
        self.spinBox_51 = QSpinBox(self.groupBox_7)
        self.spinBox_51.setObjectName(u"spinBox_51")
        self.spinBox_51.setGeometry(QRect(130, 110, 42, 22))
        self.spinBox_52 = QSpinBox(self.groupBox_7)
        self.spinBox_52.setObjectName(u"spinBox_52")
        self.spinBox_52.setGeometry(QRect(130, 150, 41, 21))
        self.spinBox_53 = QSpinBox(self.groupBox_7)
        self.spinBox_53.setObjectName(u"spinBox_53")
        self.spinBox_53.setGeometry(QRect(370, 30, 42, 22))
        self.spinBox_54 = QSpinBox(self.groupBox_7)
        self.spinBox_54.setObjectName(u"spinBox_54")
        self.spinBox_54.setGeometry(QRect(370, 70, 42, 22))
        self.spinBox_55 = QSpinBox(self.groupBox_7)
        self.spinBox_55.setObjectName(u"spinBox_55")
        self.spinBox_55.setGeometry(QRect(370, 110, 42, 22))
        self.spinBox_56 = QSpinBox(self.groupBox_7)
        self.spinBox_56.setObjectName(u"spinBox_56")
        self.spinBox_56.setGeometry(QRect(370, 150, 42, 22))
        self.Pages_Widget.addWidget(self.page_1)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.groupBox = QGroupBox(self.page_4)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(0, 20, 561, 181))
        self.groupBox.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 30, 101, 21))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 70, 101, 21))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 110, 101, 20))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 150, 101, 16))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(230, 30, 121, 16))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(230, 70, 131, 16))
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(320, 110, 31, 16))
        self.label_9 = QLabel(self.groupBox)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(320, 150, 31, 16))
        self.spinBox = QSpinBox(self.groupBox)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(130, 30, 42, 22))
        self.spinBox_2 = QSpinBox(self.groupBox)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(130, 70, 42, 22))
        self.spinBox_3 = QSpinBox(self.groupBox)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(130, 110, 42, 22))
        self.spinBox_4 = QSpinBox(self.groupBox)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(130, 150, 41, 21))
        self.spinBox_5 = QSpinBox(self.groupBox)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(370, 30, 42, 22))
        self.spinBox_6 = QSpinBox(self.groupBox)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(370, 70, 42, 22))
        self.spinBox_7 = QSpinBox(self.groupBox)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(370, 110, 42, 22))
        self.spinBox_8 = QSpinBox(self.groupBox)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(370, 150, 42, 22))
        self.label = QLabel(self.page_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(390, -10, 111, 31))
        self.label.setStyleSheet(u"font: 700 14pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(Qt.AlignCenter)
        self.graphicsView = PlotWidget(self.page_4)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(0, 210, 631, 221))
        self.pushButton = QPushButton(self.page_4)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(660, 50, 181, 51))
        self.pushButton.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.pushButton_2 = QPushButton(self.page_4)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(660, 130, 181, 51))
        self.pushButton_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.Pages_Widget.addWidget(self.page_4)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.pushButton_9 = QPushButton(self.page_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(660, 50, 181, 51))
        self.pushButton_9.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_37 = QLabel(self.page_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(390, -10, 111, 31))
        self.label_37.setStyleSheet(u"font: 700 14pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_37.setAlignment(Qt.AlignCenter)
        self.graphicsView_5 = PlotWidget(self.page_3)
        self.graphicsView_5.setObjectName(u"graphicsView_5")
        self.graphicsView_5.setGeometry(QRect(0, 210, 631, 221))
        self.pushButton_10 = QPushButton(self.page_3)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(660, 130, 181, 51))
        self.pushButton_10.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.groupBox_5 = QGroupBox(self.page_3)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(0, 20, 561, 181))
        self.groupBox_5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_38 = QLabel(self.groupBox_5)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(20, 30, 101, 21))
        self.label_39 = QLabel(self.groupBox_5)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 70, 101, 21))
        self.label_40 = QLabel(self.groupBox_5)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(20, 110, 101, 20))
        self.label_41 = QLabel(self.groupBox_5)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(20, 150, 101, 16))
        self.label_42 = QLabel(self.groupBox_5)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(230, 30, 121, 16))
        self.label_43 = QLabel(self.groupBox_5)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(230, 70, 131, 16))
        self.label_44 = QLabel(self.groupBox_5)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(320, 110, 31, 16))
        self.label_45 = QLabel(self.groupBox_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(320, 150, 31, 16))
        self.spinBox_33 = QSpinBox(self.groupBox_5)
        self.spinBox_33.setObjectName(u"spinBox_33")
        self.spinBox_33.setGeometry(QRect(130, 30, 42, 22))
        self.spinBox_34 = QSpinBox(self.groupBox_5)
        self.spinBox_34.setObjectName(u"spinBox_34")
        self.spinBox_34.setGeometry(QRect(130, 70, 42, 22))
        self.spinBox_35 = QSpinBox(self.groupBox_5)
        self.spinBox_35.setObjectName(u"spinBox_35")
        self.spinBox_35.setGeometry(QRect(130, 110, 42, 22))
        self.spinBox_36 = QSpinBox(self.groupBox_5)
        self.spinBox_36.setObjectName(u"spinBox_36")
        self.spinBox_36.setGeometry(QRect(130, 150, 41, 21))
        self.spinBox_37 = QSpinBox(self.groupBox_5)
        self.spinBox_37.setObjectName(u"spinBox_37")
        self.spinBox_37.setGeometry(QRect(370, 30, 42, 22))
        self.spinBox_38 = QSpinBox(self.groupBox_5)
        self.spinBox_38.setObjectName(u"spinBox_38")
        self.spinBox_38.setGeometry(QRect(370, 70, 42, 22))
        self.spinBox_39 = QSpinBox(self.groupBox_5)
        self.spinBox_39.setObjectName(u"spinBox_39")
        self.spinBox_39.setGeometry(QRect(370, 110, 42, 22))
        self.spinBox_40 = QSpinBox(self.groupBox_5)
        self.spinBox_40.setObjectName(u"spinBox_40")
        self.spinBox_40.setGeometry(QRect(370, 150, 42, 22))
        self.Pages_Widget.addWidget(self.page_3)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.pushButton_11 = QPushButton(self.page_2)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(660, 50, 181, 51))
        self.pushButton_11.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.label_46 = QLabel(self.page_2)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(390, -10, 111, 31))
        self.label_46.setStyleSheet(u"font: 700 14pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        self.label_46.setAlignment(Qt.AlignCenter)
        self.graphicsView_6 = PlotWidget(self.page_2)
        self.graphicsView_6.setObjectName(u"graphicsView_6")
        self.graphicsView_6.setGeometry(QRect(0, 210, 631, 221))
        self.pushButton_12 = QPushButton(self.page_2)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(660, 130, 181, 51))
        self.pushButton_12.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"font: 700 14pt \"Segoe UI\";")
        self.groupBox_6 = QGroupBox(self.page_2)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(0, 20, 561, 181))
        self.groupBox_6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_47 = QLabel(self.groupBox_6)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(20, 30, 101, 21))
        self.label_48 = QLabel(self.groupBox_6)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, 70, 101, 21))
        self.label_49 = QLabel(self.groupBox_6)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(20, 110, 101, 20))
        self.label_50 = QLabel(self.groupBox_6)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(20, 150, 101, 16))
        self.label_51 = QLabel(self.groupBox_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(230, 30, 121, 16))
        self.label_52 = QLabel(self.groupBox_6)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(230, 70, 131, 16))
        self.label_53 = QLabel(self.groupBox_6)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(320, 110, 31, 16))
        self.label_54 = QLabel(self.groupBox_6)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(320, 150, 31, 16))
        self.spinBox_41 = QSpinBox(self.groupBox_6)
        self.spinBox_41.setObjectName(u"spinBox_41")
        self.spinBox_41.setGeometry(QRect(130, 30, 42, 22))
        self.spinBox_42 = QSpinBox(self.groupBox_6)
        self.spinBox_42.setObjectName(u"spinBox_42")
        self.spinBox_42.setGeometry(QRect(130, 70, 42, 22))
        self.spinBox_43 = QSpinBox(self.groupBox_6)
        self.spinBox_43.setObjectName(u"spinBox_43")
        self.spinBox_43.setGeometry(QRect(130, 110, 42, 22))
        self.spinBox_44 = QSpinBox(self.groupBox_6)
        self.spinBox_44.setObjectName(u"spinBox_44")
        self.spinBox_44.setGeometry(QRect(130, 150, 41, 21))
        self.spinBox_45 = QSpinBox(self.groupBox_6)
        self.spinBox_45.setObjectName(u"spinBox_45")
        self.spinBox_45.setGeometry(QRect(370, 30, 42, 22))
        self.spinBox_46 = QSpinBox(self.groupBox_6)
        self.spinBox_46.setObjectName(u"spinBox_46")
        self.spinBox_46.setGeometry(QRect(370, 70, 42, 22))
        self.spinBox_47 = QSpinBox(self.groupBox_6)
        self.spinBox_47.setObjectName(u"spinBox_47")
        self.spinBox_47.setGeometry(QRect(370, 110, 42, 22))
        self.spinBox_48 = QSpinBox(self.groupBox_6)
        self.spinBox_48.setObjectName(u"spinBox_48")
        self.spinBox_48.setGeometry(QRect(370, 150, 42, 22))
        self.Pages_Widget.addWidget(self.page_2)

        self.verticalLayout_5.addWidget(self.Pages_Widget)


        self.horizontalLayout_2.addWidget(self.frame_pages)


        self.verticalLayout.addWidget(self.Content)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.Pages_Widget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(lambda:self.draw())
        self.pushButton_2.clicked.connect(lambda:self.clear())

        
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Btn_Toggle.setText(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.btn_page_4.setText(QCoreApplication.translate("MainWindow", u"AOO", None))
        self.btn_page_3.setText(QCoreApplication.translate("MainWindow", u"VOO", None))
        self.btn_page_2.setText(QCoreApplication.translate("MainWindow", u"AAI", None))
        self.btn_page_1.setText(QCoreApplication.translate("MainWindow", u"VVI", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.label_55.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>AOO</p></body></html>", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_56.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_57.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_58.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_59.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_60.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_61.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_62.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_63.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:16pt; font-weight:700; color:#ffffff;\">VVI</span></p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>AAI</p></body></html>", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"Create Graph", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>VOO</p></body></html>", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"Clear", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Parameters", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Lower Rate Limit", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Upper Rate Limit", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Atrial Amplitude", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Atrial Pulse Width", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Ventricular Amplitude", None))
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"Ventricular Pulse Width", None))
        self.label_53.setText(QCoreApplication.translate("MainWindow", u"VRP", None))
        self.label_54.setText(QCoreApplication.translate("MainWindow", u"ARP", None))
    # retranslateUi


    def draw(self):
        x = np.random.normal(size=1000)
        y = np.random.normal(size=(3,1000))
        for i in range(3):
            self.graphicsView.plot(x,y[i],pen=(i,3))

    def clear(self):
        self.graphicsView.clear()




    

